//! This file provides various Vulkan wrappers and helpers.
const c = @import("c.zig");

pub inline fn deviceWaitIdle(device: c.VkDevice) !Result {
    return try castResult(c.vkDeviceWaitIdle.?(device));
}

/// Queue wrapper providing queue family index and VkQueue handle.
pub const Queue = struct {
    index: u32,
    handle: c.VkQueue = null,
};

/// Non-error VkResult values wrapped as enum.
pub const Result = enum {
    success,
    not_ready,
    timeout,
    event_set,
    event_reset,
    incomplete,
    pipeline_compile_required,
    suboptimal_khr,
    thread_idle_khr,
    thread_done_khr,
    operation_deferred_khr,
    operation_not_deferred_khr,
    incompatible_shader_binary_ext,
    pipeline_binary_missing_khr,
};

/// Error VkResult values wrapped as error.
pub const Error = error{
    OutOfHostMemory,
    OutOfDeviceMemory,
    InitializationFailed,
    DeviceLost,
    MemoryMapFailed,
    LayerNotPresent,
    ExtensionNotPresent,
    FeatureNotPresent,
    IncompatibleDriver,
    TooManyObjects,
    FormatNotSupported,
    FragmentedPool,
    Unknown,
    OutOfPoolMemory,
    InvalidExternalHandle,
    Fragmentation,
    InvalidOpaqueCaptureAddress,
    NotPermitted,
    SurfaceLostKHR,
    NativeWindowInUseKHR,
    OutOfDateKHR,
    IncompatibleDisplayKHR,
    ValidationFailedEXT,
    InvalidShaderNV,
    ImageUsageNotSupportedKHR,
    VideoPictureLayoutNotSupportedKHR,
    VideoProfileOperationNotSupportedKHR,
    VideoProfileFormatNotSupportedKHR,
    VideoProfileCodecNotSupportedKHR,
    VideoSTDVersionNotSupportedKHR,
    InvalidDRMFormatModifierPlaneLayoutEXT,
    FullScreenExclusiveModeLostEXT,
    InvalidVideoSTDParametersKHR,
    CompressionExhaustedEXT,
    NotEnoughSpaceKHR,
};

/// Cast c.VkResult value into vk.Result or vk.Error.
pub fn castResult(result: c.VkResult) !Result {
    return switch (result) {
        c.VK_SUCCESS => .success,
        c.VK_NOT_READY => .not_ready,
        c.VK_TIMEOUT => .timeout,
        c.VK_EVENT_SET => .event_set,
        c.VK_EVENT_RESET => .event_reset,
        c.VK_INCOMPLETE => .incomplete,
        c.VK_ERROR_OUT_OF_HOST_MEMORY => error.OutOfHostMemory,
        c.VK_ERROR_OUT_OF_DEVICE_MEMORY => error.OutOfDeviceMemory,
        c.VK_ERROR_INITIALIZATION_FAILED => error.InitializationFailed,
        c.VK_ERROR_DEVICE_LOST => error.DeviceLost,
        c.VK_ERROR_MEMORY_MAP_FAILED => error.MemoryMapFailed,
        c.VK_ERROR_LAYER_NOT_PRESENT => error.LayerNotPresent,
        c.VK_ERROR_EXTENSION_NOT_PRESENT => error.ExtensionNotPresent,
        c.VK_ERROR_FEATURE_NOT_PRESENT => error.FeatureNotPresent,
        c.VK_ERROR_INCOMPATIBLE_DRIVER => error.IncompatibleDriver,
        c.VK_ERROR_TOO_MANY_OBJECTS => error.TooManyObjects,
        c.VK_ERROR_FORMAT_NOT_SUPPORTED => error.FormatNotSupported,
        c.VK_ERROR_FRAGMENTED_POOL => error.FragmentedPool,
        c.VK_ERROR_UNKNOWN => error.Unknown,
        c.VK_ERROR_OUT_OF_POOL_MEMORY => error.OutOfPoolMemory,
        c.VK_ERROR_INVALID_EXTERNAL_HANDLE => error.InvalidExternalHandle,
        c.VK_ERROR_FRAGMENTATION => error.Fragmentation,
        c.VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS => error.InvalidOpaqueCaptureAddress,
        c.VK_PIPELINE_COMPILE_REQUIRED => .pipeline_compile_required,
        c.VK_ERROR_NOT_PERMITTED => error.NotPermitted,
        c.VK_ERROR_SURFACE_LOST_KHR => error.SurfaceLostKHR,
        c.VK_ERROR_NATIVE_WINDOW_IN_USE_KHR => error.NativeWindowInUseKHR,
        c.VK_SUBOPTIMAL_KHR => .suboptimal_khr,
        c.VK_ERROR_OUT_OF_DATE_KHR => error.OutOfDateKHR,
        c.VK_ERROR_INCOMPATIBLE_DISPLAY_KHR => error.IncompatibleDisplayKHR,
        c.VK_ERROR_VALIDATION_FAILED_EXT => error.ValidationFailedEXT,
        c.VK_ERROR_INVALID_SHADER_NV => error.InvalidShaderNV,
        c.VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR => error.ImageUsageNotSupportedKHR,
        c.VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR => error.VideoPictureLayoutNotSupportedKHR,
        c.VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR => error.VideoProfileOperationNotSupportedKHR,
        c.VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR => error.VideoProfileFormatNotSupportedKHR,
        c.VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR => error.VideoProfileCodecNotSupportedKHR,
        c.VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR => error.VideoSTDVersionNotSupportedKHR,
        c.VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT => error.InvalidDRMFormatModifierPlaneLayoutEXT,
        c.VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT => error.FullScreenExclusiveModeLostEXT,
        c.VK_THREAD_IDLE_KHR => .thread_idle_khr,
        c.VK_THREAD_DONE_KHR => .thread_done_khr,
        c.VK_OPERATION_DEFERRED_KHR => .operation_deferred_khr,
        c.VK_OPERATION_NOT_DEFERRED_KHR => .operation_not_deferred_khr,
        c.VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR => error.InvalidVideoSTDParametersKHR,
        c.VK_ERROR_COMPRESSION_EXHAUSTED_EXT => error.CompressionExhaustedEXT,
        c.VK_INCOMPATIBLE_SHADER_BINARY_EXT => .incompatible_shader_binary_ext,
        c.VK_PIPELINE_BINARY_MISSING_KHR => .pipeline_binary_missing_khr,
        c.VK_ERROR_NOT_ENOUGH_SPACE_KHR => error.NotEnoughSpaceKHR,
        else => error.Unknown,
    };
}
