[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
vk-mem = { git = "https://github.com/SimonBorghese/vk-mem-rs.git", rev = "5062f0bc3009f8c5dfaebd7c8da27c22ba6379ec" }
winit = "0.30.5"
